"""
This script aggregates the ATE and RPE results
from experiments done on across multiple datasets,
in both monocular and stereo configurations.

It generates RPE/ATE tables that can be directly included
in a Latex document.

The expected input formats are the CSV files generated by
error_comparison, which are:
    - ate_results.csv: contains mean ATE values for each algorithm/dataset/cam_config combination
    - rpe_results.csv: contains mean RPE values for each algorithm/dataset/cam_config/segment_m combination
    - rpe_raw_samples.csv: contains the raw RPE error samples for each segment.

The algorithms are expected to be in the format: 
    - (base_algorithm)__1cam for monocular results
    - (base_algorithm)__2cam for stereo results

This script will then generate separate tables for mono and stereo,
as well as a combined table that shows the mono and stereo results side-by-side for 
easier comparison.
"""
import yaml
import os
import argparse
import subprocess
import logging
import matplotlib.pyplot as plt
import seaborn as sns

from pyvins.file_utils import get_all_subdirectory_names
from pyvins.plot_utils import set_plot_theme
from pyvins.tables import create_ate_table, create_combined_ate_table, create_rpe_table
from pyvins.processing import get_label_for_alg

import pandas as pd
import typing

colors = set_plot_theme(palette="colorblind", enable_latex=True,)

logging.basicConfig(level=logging.INFO)


def generate_ate_table(
    path_csv: str,
    datasets: typing.List[str],
    algorithms: typing.List[str],
    labels: typing.List[str],
    output_path: str,
):
    """Load the ATE results from the CSV and create LaTeX tables for mono and stereo."""
    if not os.path.exists(path_csv):
        logging.error(f"CSV file not found: {path_csv}")
        exit(1)

    df = pd.read_csv(path_csv)

    # Split algorithm column into base name and camera config
    df[["base_algorithm", "cam_config"]] = df["algorithm"].str.split(
        "__", n=1, expand=True
    )

    if datasets is not None:
        df = df[df["dataset"].isin(datasets)]
    if algorithms is not None:
        df = df[df["base_algorithm"].isin(algorithms)]

    label_map = {}
    if algorithms is not None and labels is not None:
        label_map = dict(zip(algorithms, labels))

    algo_order = [label_map.get(a, a) for a in algorithms] if algorithms else None

    def _build_and_save_table(df_subset, path_suffix):
        results_by_dataset = {}
        for _, row in df_subset.iterrows():
            dataset = row["dataset"]
            algo = label_map.get(row["base_algorithm"], row["base_algorithm"])
            results_by_dataset.setdefault(dataset, {})[algo] = {
                "ate_ori": row["mean_ori"],
                "ate_pos": row["mean_pos"],
            }
        latex_table = create_ate_table(
            results_by_dataset,
            include_average=True,
            algorithm_order=algo_order,
            bold_best=True,
        )
        print(latex_table)
        base, ext = os.path.splitext(output_path)
        save_path = f"{base}_{path_suffix}{ext}"
        with open(save_path, "w") as f:
            f.write(latex_table)
        logging.info(f"ATE LaTeX table saved to {save_path}")

    _build_and_save_table(df[df["cam_config"] == "1cam"], "mono")
    _build_and_save_table(df[df["cam_config"] == "2cam"], "stereo")

    def _build_results(df_subset):
        results = {}
        for _, row in df_subset.iterrows():
            dataset = row["dataset"]
            algo = label_map.get(row["base_algorithm"], row["base_algorithm"])
            results.setdefault(dataset, {})[algo] = {
                "ate_ori": row["mean_ori"],
                "ate_pos": row["mean_pos"],
            }
        return results

    combined_table = create_combined_ate_table(
        mono_results=_build_results(df[df["cam_config"] == "1cam"]),
        stereo_results=_build_results(df[df["cam_config"] == "2cam"]),
        include_average=True,
        algorithm_order=algo_order,
        bold_best=True,
    )
    print(combined_table)
    base, ext = os.path.splitext(output_path)
    combined_path = f"{base}_combined{ext}"
    with open(combined_path, "w") as f:
        f.write(combined_table)
    logging.info(f"Combined ATE LaTeX table saved to {combined_path}")


def load_rpe_results(
    rpe_csv_file: str,
    algorithms: typing.List[str],
    labels: typing.List[str],
    output_path: str,
):
    df = pd.read_csv(rpe_csv_file)

    # Split algorithm column into base name and camera config
    df[["base_algorithm", "cam_config"]] = df["algorithm"].str.split(
        "__", n=1, expand=True
    )

    label_map = {}
    if algorithms is not None and labels is not None:
        label_map = dict(zip(algorithms, labels))

    def _build_and_save_table(df_subset, path_suffix):
        rpe_results_by_segment = {}
        for seg, group in df_subset.groupby("segment_m"):
            rpe_results_by_segment[seg] = {
                label_map.get(
                    row["base_algorithm"], row["base_algorithm"]
                ): row.to_dict()
                for _, row in group.iterrows()
            }
        table = create_rpe_table(rpe_results_by_segment, bold_best=True)
        print(table)
        base, ext = os.path.splitext(output_path)
        save_path = f"{base}_{path_suffix}{ext}"
        with open(save_path, "w") as f:
            f.write(table)
        logging.info(f"RPE LaTeX table saved to {save_path}")

    _build_and_save_table(df[df["cam_config"] == "1cam"], "mono")
    _build_and_save_table(df[df["cam_config"] == "2cam"], "stereo")


def generate_rpe_boxplot(
    rpe_samples_csv_file: str,
    algorithms: typing.List[str],
    labels: typing.List[str],
    save_fig_path: str,
):
    df = pd.read_csv(rpe_samples_csv_file)

    # Split the algorithm column into base name and camera config (e.g. "1cam" / "2cam")
    df[["base_algorithm", "cam_config"]] = df["algorithm"].str.split(
        "__", n=1, expand=True
    )

    # Split into mono and stereo subsets
    df_mono = df[df["cam_config"] == "1cam"].copy()
    df_stereo = df[df["cam_config"] == "2cam"].copy()

    # Build label map keyed on base algorithm name (no __xcam suffix needed from the caller)
    if algorithms is not None and labels is not None:
        label_map = dict(zip(algorithms, labels))
        df_mono["base_algorithm"] = (
            df_mono["base_algorithm"].map(label_map).fillna(df_mono["base_algorithm"])
        )
        df_stereo["base_algorithm"] = (
            df_stereo["base_algorithm"]
            .map(label_map)
            .fillna(df_stereo["base_algorithm"])
        )
        hue_order = [label_map.get(a, a) for a in algorithms]
    else:
        hue_order = sorted(df["base_algorithm"].unique().tolist())

    metrics = [
        ("ori_error", "Attitude Error (deg)"),
        ("pos_error", "Position Error (m)"),
    ]
    cam_configs = [(df_mono, "Monocular"), (df_stereo, "Stereo")]

    def _make_boxplot_figure(df_subset, title_suffix):
        fig, axes = plt.subplots(2, 1, figsize=(13, 6))
        for ax, (col, ylabel) in zip(axes, metrics):
            sns.boxplot(
                data=df_subset,
                x="segment_m",
                y=col,
                hue="base_algorithm",
                ax=ax,
                fill=False,
                width=0.7,
                gap=0.3,
                showfliers=False,
                hue_order=hue_order,
                palette=colors,
                linewidth=1.0,
            )
            ax.set_title(f"Relative {ylabel.split()[0]} Error ({title_suffix})")
            ax.set_ylabel(ylabel)
            ax.set_xlabel("Segment Length (m)")

        axes[1].get_legend().remove()
        axes[0].legend(bbox_to_anchor=(1.01, 1), loc="upper left", borderaxespad=0)
        fig.tight_layout()
        return fig

    base, ext = os.path.splitext(save_fig_path)

    fig_mono = _make_boxplot_figure(df_mono, "Monocular")
    mono_path = f"{base}_mono{ext}"
    fig_mono.savefig(mono_path, bbox_inches="tight", dpi=300)
    logging.info(f"Mono RPE boxplot saved to {mono_path}")

    fig_stereo = _make_boxplot_figure(df_stereo, "Stereo")
    stereo_path = f"{base}_stereo{ext}"
    fig_stereo.savefig(stereo_path, bbox_inches="tight", dpi=300)
    logging.info(f"Stereo RPE boxplot saved to {stereo_path}")

    # Combined 2x2: rows = metric (ori / pos), columns = cam config (mono / stereo)
    fig_combined, axes_grid = plt.subplots(2, 2, figsize=(15, 7), sharey="row")
    for col_idx, (df_subset, col_title) in enumerate(cam_configs):
        for row_idx, (metric_col, ylabel) in enumerate(metrics):
            ax = axes_grid[row_idx, col_idx]
            sns.boxplot(
                data=df_subset,
                x="segment_m",
                y=metric_col,
                hue="base_algorithm",
                ax=ax,
                fill=False,
                width=0.8,
                gap=0.15,
                showfliers=False,
                hue_order=hue_order,
                palette=colors,
                linewidth=1.5,
            )
            ax.set_title(col_title if row_idx == 0 else "")
            ax.set_ylabel(ylabel if col_idx == 0 else "")
            ax.set_xlabel("Segment Length (m)" if row_idx == 1 else "")

    # Mirror the same legend approach used in _make_boxplot_figure:
    # remove all but one, then reposition that one outside the axes.
    for ax in axes_grid.flat:
        leg = ax.get_legend()
        if leg is not None:
            leg.remove()
    axes_grid[0, 1].legend(bbox_to_anchor=(1.01, 1), loc="upper left", borderaxespad=0)
    fig_combined.tight_layout()
    fig_combined.savefig(save_fig_path, bbox_inches="tight", dpi=600)
    logging.info(f"Combined RPE boxplot saved to {save_fig_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluate SLAM results on real data, generates CSV files and outputs table for the paper."
    )
    parser.add_argument(
        "--results_folder",
        default=None,
        help="Path to the folder containing algorithm subfolders with results.",
    )
    parser.add_argument(
        "--algorithms",
        nargs="+",
        default=None,
        help="Subset of algorithm names to include. If omitted, all algorithms are used.",
    )
    parser.add_argument(
        "--labels_map_yaml",
        type=str,
        default=None,
        help="Path to yaml file mapping algorithm names to labels for plotting",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=None,
        help="Subset of dataset names to include. If omitted, all datasets are used.",
    )
    parser.add_argument("--output", default=None, help="Path to save the LaTeX table.")
    args = parser.parse_args()

    # Load the CSV file for the ATE
    if args.algorithms is None:
        df_ate = pd.read_csv(os.path.join(args.results_folder, "ate_results.csv"))
        args.algorithms = sorted(df_ate["algorithm"].str.split("__", n=1).str[0].unique())
        print(f"Discovered algorithms: {args.algorithms}")

    if args.datasets is None:
        df_ate = pd.read_csv(os.path.join(args.results_folder, "ate_results.csv"))
        args.datasets = sorted(df_ate["dataset"].unique())
        print(f"Discovered datasets: {args.datasets}")

    if args.labels_map_yaml is not None:
        with open(args.labels_map_yaml, "r") as f:
            labels_map = yaml.safe_load(f)
        args.labels = [labels_map.get(a, a) for a in args.algorithms]
    else:
        args.labels = [get_label_for_alg(a) for a in args.algorithms]
    # Load the labels map from the YAML file
    print(f"Using labels: {args.labels}")

    # # Generate RPE table
    path_csv_rpe = os.path.join(args.results_folder, "rpe_results.csv")
    output_path_rpe = os.path.join(args.results_folder, "rpe_table.txt")
    load_rpe_results(path_csv_rpe, args.algorithms, args.labels, output_path_rpe)

    # Generate ATE table
    path_csv = os.path.join(args.results_folder, "ate_results.csv")
    output_path = os.path.join(args.results_folder, "ate_table.txt")
    generate_ate_table(
        path_csv,
        datasets=args.datasets,
        algorithms=args.algorithms,
        labels=args.labels,
        output_path=output_path,
    )

    ### Generate RPE boxplot figure
    rpe_samples_csv_file = os.path.join(args.results_folder, "rpe_raw_samples.csv")
    save_fig_path = os.path.join(args.results_folder, "rpe_boxplot.pdf")
    generate_rpe_boxplot(
        rpe_samples_csv_file,
        args.algorithms,
        args.labels,
        save_fig_path,
    )
    plt.show()
